### ISSUE TITLE
Perl EAPI=4 issue.

### ISSUE THREAD

**Issue by keesats** [KsenZ/gentoo-overlay#1]
I installed Gentoo, added this overlay and was unable to install the PacManager package. All of the Perl ebuilds begin with the line: EAPI=4, which is not supported by the latest version of Perl on the Gentoo system. As of this writing, I'm unable to use this overlay to load the Pac Manager app, it fails because of this error.

Thanks!

**Comment by KsenZ** [comment]
I remove PacManager, and add Asbru CM https://github.com/asbru-cm/asbru-cm
